# The URL the site will be built for
base_url = "https://danielcordova.me/"

title = "Daniel Cordova"

output_dir = "public"
compile_sass = true
minify_html = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

exclude_paginated_pages_in_sitemap = "all"
build_search_index = true

# Feed
generate_feeds = false
feed_filenames = ["atom.xml", "rss.xml"]

generate_sitemap = true
generate_robots_txt = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
highlight_code = true
highlight_theme = "nord"

[search]
include_title = true
include_description = false
include_date = false
include_path = true
include_content = true
index_format = "fuse_json"

[extra]
toc = true
author = "Daniel Cordova"
recent_size = 5
github_link = "https://github.com/dcdaz"